Import('env')

# Build sdk library
test = env.Program('sanskrit', 
   Glob('*.c', strings=True),
   CPPPATH = ['.'] + env['SANSKRIT_INCLUDE'],
   CPPDEFINES=["SKLOG_SYSLOG"],
   CCFLAGS = ['-std=c89','-Werror','-pedantic','-ggdb'],
   LIBPATH= env['SANSKRIT_LIB'],
   LIBS = ['sanskrit']
)
