Import('env')

# Build sdk library
test = env.Program('sanskrit', 
   Glob('*.c', strings=True),
   CPPPATH = ['.'] + env['SANSKRIT_INCLUDE'],
   CCFLAGS = ['-std=c89','-Werror','-pedantic','-ggdb'],
)
